### ISSUE TITLE
Support of v3 final spec

### ISSUE THREAD

**Issue by StenGruener** [aas-core-works/aas-core3.0-csharp#15]
Hi @mristin,

thanks for doing this! Is there some timeline when the support for the final release of the metamodel is expected? https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf ?

BR
Sten

**Comment by mristin** [comment]
@StenGruener I have to double-check,  but I think this _is_ already the final model. I'll regenerate everything on roughly May 6th, just to be on the safe side.

**Comment by mristin** [comment]
@StenGruener you have to use https://github.com/aas-core-works/aas-package3-csharp for managing AASX. 

Please bear in mind that Open Packaging Convention, the format underlying AASX, is not supported by Microsoft anymore, and has not been implemented in any other language than C#. 

It is very likely that it will be discontinued soon as the format for AASX.

**Comment by mristin** [comment]
@StenGruener the last commit in python-opc was 10 years ago. Microsoft itself does not support their own format, so I doubt IDTA will keep maintaining it in any sensible way.

So far, the package library should be 100% conformant to the specs.

**Comment by StenGruener** [comment]
Thank you for the comments on the library.

Continuing the off-topic: sorry i mixed up with https://github.com/acplt/PyECMA376-2 which is a pretty active package. For Java there is an apache lib: https://poi.apache.org/components/oxml4j/index.html. Do you have any more information on the deprecation of the ecma-376?

anyway

**Comment by mristin** [comment]
@s-heppner could you please shed some light on status / progress of PyECMA376-2?

**Comment by mhthies** [comment]
Well, PyECMA376-2 is nearly feature complete: I left out the cryptographic signature part of t ECMA376-2 (section 10 of the spec), as that would have required a full implementation of W3C's "XML Signature Syntax and Processing Version 1.1" spec.

Apart from that, PyECMA376-2 should be feature complete with regard to the ECMA376-2 specification, including all the package metadata like MIME typesm and semantic relationships. I did my best to make it maintainable and well-tested. However, since I (luckily) don't have any contact with any OPC-based file formats anymore, I will probably not provide any maintenance for this library in the future.
